apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgresql
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: postgresql.postgres.svc.cluster.local
    database.port: 5432
    database.user: debezium
    database.password: debezium
    database.dbname: debezium
    topic.prefix: debezium.testdb.inventory
    plugin.name: pgoutput
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
    #schema.history.internal.kafka.topic: schema-changes.inventory
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: false
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: false
    transforms: RemoveTableNameFromTopicName
    transforms.RemoveTableNameFromTopicName.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.RemoveTableNameFromTopicName.regex: debezium.testdb.inventory.*
    transforms.RemoveTableNameFromTopicName.replacement: debezium.testdb.inventory