apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: debezium-connector-postgresql
  namespace: kafka
  labels:
    strimzi.io/cluster: debezium-connect-cluster
spec:
  class: io.debezium.connector.postgresql.PostgresConnector
  tasksMax: 1
  config:
    tasks.max: 1
    offset.storage.file.filename: /debezium/data/offsets.dat
    database.history: io.debezium.relational.history.FileDatabaseHistory
    database.hostname: postgresql.postgres.svc.cluster.local
    database.port: 5432
    database.user: debezium
    database.password: debezium
    database.dbname: debezium
    topic.prefix: postgres
    database.include.list: inventory
    schema.history.internal.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.inventory