apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: debezium-connect-cluster-elastic
  namespace: kafka
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.7.0
  replicas: 1
  bootstrapServers: my-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
  config:
    config.providers: secrets
    config.providers.secrets.class: io.strimzi.kafka.KubernetesSecretConfigProvider
    group.id: connect-cluster-elastic
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
    # -1 means it will use the default replication factor configured in the broker
    config.storage.replication.factor: -1
    offset.storage.replication.factor: -1
    status.storage.replication.factor: -1
  build:
    output:
      type: docker
      image: serhattural/kafka-connect-elastic-sink:1.0.1
      pushSecret: serhattural-docker-secret
    plugins:
      - name: debezium-elastic-connector
        artifacts:
          - type: jar
            #url: https://github.com/ibm-messaging/kafka-connect-elastic-sink/releases/download/v1.0.1/kafka-connect-elastic-sink-1.0.1-jar-with-dependencies.jar
            url: https://packages.confluent.io/maven/io/confluent/kafka-connect-elasticsearch/14.0.3/kafka-connect-elasticsearch-14.0.3.jar
            